import { DataTable } from "@/components/features/ProductTable/DataTable";
import { Button } from "@/components/ui/button";
import { dealsColumns } from "@/components/features/DealsTable/DealsColumns";
import { TypographyH2 } from "@/components/Typography/Typography";
import { useState } from "react";
import AddDeal from "@/components/features/DealModel";
import UpdateDeal from "@/components/features/UpdateDeal";

export const dummyDealsData = [
  {
    id: "DL-001",
    image: "deal-1.jpg",
    dealName: "Summer Blast",
    title: "Limited Edition",
    variantsIncluded: "12 Products",
    dealPrice: 4999.0,
    regularPrice: 7999.0,
    saving: { amount: 3000.0, percentage: 37.5 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-002",
    image: "deal-2.jpg",
    dealName: "Winter Special",
    title: "Cold Weather Combo",
    variantsIncluded: "8 Products",
    dealPrice: 3499.0,
    regularPrice: 5999.0,
    saving: { amount: 2500.0, percentage: 41.67 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-003",
    image: "deal-3.jpg",
    dealName: "Eid Mubarak",
    title: "Festival Bundle",
    variantsIncluded: "15 Products",
    dealPrice: 8999.0,
    regularPrice: 12999.0,
    saving: { amount: 4000.0, percentage: 30.77 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-004",
    image: "deal-4.jpg",
    dealName: "Black Friday",
    title: "Mega Sale",
    variantsIncluded: "25 Products",
    dealPrice: 19999.0,
    regularPrice: 34999.0,
    saving: { amount: 15000.0, percentage: 42.86 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-005",
    image: "deal-5.jpg",
    dealName: "New Year Deal",
    title: "2025 Special",
    variantsIncluded: "10 Products",
    dealPrice: 5999.0,
    regularPrice: 9999.0,
    saving: { amount: 4000.0, percentage: 40.0 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-006",
    image: "deal-6.jpg",
    dealName: "Weekend Flash",
    title: "Limited Time",
    variantsIncluded: "5 Products",
    dealPrice: 2499.0,
    regularPrice: 3999.0,
    saving: { amount: 1500.0, percentage: 37.51 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-007",
    image: "deal-7.jpg",
    dealName: "Clearance Sale",
    title: "Last Chance",
    variantsIncluded: "20 Products",
    dealPrice: 4999.0,
    regularPrice: 14999.0,
    saving: { amount: 10000.0, percentage: 66.67 },
    status: "Expired",
    createdBy: "Admin",
  },
  {
    id: "DL-008",
    image: "deal-8.jpg",
    dealName: "Buy 1 Get 1",
    title: "Limited Offer",
    variantsIncluded: "Custom Deal",
    dealPrice: 2999.0,
    regularPrice: 5999.0,
    saving: { amount: 3000.0, percentage: 50.0 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-009",
    image: "deal-9.jpg",
    dealName: "Student Special",
    title: "Education Discount",
    variantsIncluded: "6 Products",
    dealPrice: 1499.0,
    regularPrice: 2499.0,
    saving: { amount: 1000.0, percentage: 40.02 },
    status: "Inactive",
    createdBy: "Admin",
  },
  {
    id: "DL-010",
    image: "deal-10.jpg",
    dealName: "Ramadan Offer",
    title: "Special Bundle",
    variantsIncluded: "12 Products",
    dealPrice: 7499.0,
    regularPrice: 10999.0,
    saving: { amount: 3500.0, percentage: 31.82 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-011",
    image: "deal-11.jpg",
    dealName: "Cyber Monday",
    title: "Tech Deals",
    variantsIncluded: "18 Products",
    dealPrice: 15999.0,
    regularPrice: 24999.0,
    saving: { amount: 9000.0, percentage: 36.0 },
    status: "Expired",
    createdBy: "Manager",
  },
  {
    id: "DL-012",
    image: "deal-12.jpg",
    dealName: "Valentine's Day",
    title: "Love Bundle",
    variantsIncluded: "8 Products",
    dealPrice: 3999.0,
    regularPrice: 6999.0,
    saving: { amount: 3000.0, percentage: 42.86 },
    status: "Inactive",
    createdBy: "Admin",
  },
  {
    id: "DL-013",
    image: "deal-13.jpg",
    dealName: "Holiday Special",
    title: "Christmas Pack",
    variantsIncluded: "14 Products",
    dealPrice: 8999.0,
    regularPrice: 12999.0,
    saving: { amount: 4000.0, percentage: 30.77 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-014",
    image: "deal-14.jpg",
    dealName: "Weekend Warrior",
    title: "Sports Deal",
    variantsIncluded: "7 Products",
    dealPrice: 4499.0,
    regularPrice: 6999.0,
    saving: { amount: 2500.0, percentage: 35.72 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-015",
    image: "deal-15.jpg",
    dealName: "Family Pack",
    title: "Group Discount",
    variantsIncluded: "22 Products",
    dealPrice: 12499.0,
    regularPrice: 19999.0,
    saving: { amount: 7500.0, percentage: 37.5 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-016",
    image: "deal-16.jpg",
    dealName: "Birthday Bash",
    title: "Celebration Deal",
    variantsIncluded: "Custom Deal",
    dealPrice: 1999.0,
    regularPrice: 2999.0,
    saving: { amount: 1000.0, percentage: 33.34 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-017",
    image: "deal-17.jpg",
    dealName: "Anniversary Sale",
    title: "Year End",
    variantsIncluded: "30 Products",
    dealPrice: 29999.0,
    regularPrice: 49999.0,
    saving: { amount: 20000.0, percentage: 40.0 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-018",
    image: "deal-18.jpg",
    dealName: "Morning Coffee",
    title: "Breakfast Deal",
    variantsIncluded: "4 Products",
    dealPrice: 899.0,
    regularPrice: 1499.0,
    saving: { amount: 600.0, percentage: 40.03 },
    status: "Inactive",
    createdBy: "Manager",
  },
  {
    id: "DL-019",
    image: "deal-19.jpg",
    dealName: "Midnight Madness",
    title: "Night Owl",
    variantsIncluded: "9 Products",
    dealPrice: 5499.0,
    regularPrice: 8999.0,
    saving: { amount: 3500.0, percentage: 38.89 },
    status: "Expired",
    createdBy: "Admin",
  },
  {
    id: "DL-020",
    image: "deal-20.jpg",
    dealName: "Back to School",
    title: "Education Pack",
    variantsIncluded: "16 Products",
    dealPrice: 6499.0,
    regularPrice: 9999.0,
    saving: { amount: 3500.0, percentage: 35.0 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-021",
    image: "deal-21.jpg",
    dealName: "Fitness Freak",
    title: "Gym Bundle",
    variantsIncluded: "11 Products",
    dealPrice: 7999.0,
    regularPrice: 12999.0,
    saving: { amount: 5000.0, percentage: 38.46 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-022",
    image: "deal-22.jpg",
    dealName: "Gaming Zone",
    title: "Pro Gamer",
    variantsIncluded: "Custom Deal",
    dealPrice: 14999.0,
    regularPrice: 24999.0,
    saving: { amount: 10000.0, percentage: 40.0 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-023",
    image: "deal-23.jpg",
    dealName: "Pet Lover",
    title: "Animal Care",
    variantsIncluded: "7 Products",
    dealPrice: 2999.0,
    regularPrice: 4999.0,
    saving: { amount: 2000.0, percentage: 40.01 },
    status: "Inactive",
    createdBy: "Manager",
  },
  {
    id: "DL-024",
    image: "deal-24.jpg",
    dealName: "Home Office",
    title: "Work From Home",
    variantsIncluded: "13 Products",
    dealPrice: 8999.0,
    regularPrice: 13999.0,
    saving: { amount: 5000.0, percentage: 35.72 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-025",
    image: "deal-25.jpg",
    dealName: "Kitchen King",
    title: "Cooking Set",
    variantsIncluded: "19 Products",
    dealPrice: 11999.0,
    regularPrice: 17999.0,
    saving: { amount: 6000.0, percentage: 33.34 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-026",
    image: "deal-26.jpg",
    dealName: "Beauty Box",
    title: "Cosmetics Deal",
    variantsIncluded: "15 Products",
    dealPrice: 4499.0,
    regularPrice: 7499.0,
    saving: { amount: 3000.0, percentage: 40.01 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-027",
    image: "deal-27.jpg",
    dealName: "Gardening Gift",
    title: "Plant Lover",
    variantsIncluded: "8 Products",
    dealPrice: 3499.0,
    regularPrice: 5499.0,
    saving: { amount: 2000.0, percentage: 36.37 },
    status: "Inactive",
    createdBy: "Admin",
  },
  {
    id: "DL-028",
    image: "deal-28.jpg",
    dealName: "Travel Bug",
    title: "Vacation Pack",
    variantsIncluded: "Custom Deal",
    dealPrice: 24999.0,
    regularPrice: 39999.0,
    saving: { amount: 15000.0, percentage: 37.5 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-029",
    image: "deal-29.jpg",
    dealName: "Baby Bundle",
    title: "New Parent",
    variantsIncluded: "12 Products",
    dealPrice: 5499.0,
    regularPrice: 8999.0,
    saving: { amount: 3500.0, percentage: 38.89 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-030",
    image: "deal-30.jpg",
    dealName: "Eco Friendly",
    title: "Green Deal",
    variantsIncluded: "9 Products",
    dealPrice: 3999.0,
    regularPrice: 6499.0,
    saving: { amount: 2500.0, percentage: 38.47 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-031",
    image: "deal-31.jpg",
    dealName: "Luxury Life",
    title: "Premium Pack",
    variantsIncluded: "24 Products",
    dealPrice: 49999.0,
    regularPrice: 79999.0,
    saving: { amount: 30000.0, percentage: 37.5 },
    status: "Expired",
    createdBy: "Manager",
  },
  {
    id: "DL-032",
    image: "deal-32.jpg",
    dealName: "Minimalist",
    title: "Less is More",
    variantsIncluded: "3 Products",
    dealPrice: 999.0,
    regularPrice: 1499.0,
    saving: { amount: 500.0, percentage: 33.36 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-033",
    image: "deal-33.jpg",
    dealName: "Tech Guru",
    title: "Gadget Lover",
    variantsIncluded: "20 Products",
    dealPrice: 29999.0,
    regularPrice: 49999.0,
    saving: { amount: 20000.0, percentage: 40.0 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-034",
    image: "deal-34.jpg",
    dealName: "Artisan Pick",
    title: "Handcrafted",
    variantsIncluded: "Custom Deal",
    dealPrice: 6499.0,
    regularPrice: 9999.0,
    saving: { amount: 3500.0, percentage: 35.0 },
    status: "Inactive",
    createdBy: "Manager",
  },
  {
    id: "DL-035",
    image: "deal-35.jpg",
    dealName: "Vintage Vibes",
    title: "Retro Collection",
    variantsIncluded: "10 Products",
    dealPrice: 7499.0,
    regularPrice: 11999.0,
    saving: { amount: 4500.0, percentage: 37.5 },
    status: "Active",
    createdBy: "Admin",
  },
  {
    id: "DL-036",
    image: "deal-36.jpg",
    dealName: "Zero Waste",
    title: "Sustainable",
    variantsIncluded: "6 Products",
    dealPrice: 1999.0,
    regularPrice: 2999.0,
    saving: { amount: 1000.0, percentage: 33.34 },
    status: "Active",
    createdBy: "Manager",
  },
  {
    id: "DL-037",
    image: "deal-37.jpg",
    dealName: "Coffee Addict",
    title: "Brew Bundle",
    variantsIncluded: "5 Products",
    dealPrice: 1499.0,
    regularPrice: 2499.0,
    saving: { amount: 1000.0, percentage: 40.02 },
    status: "Expired",
    createdBy: "Admin",
  },
  {
    id: "DL-038",
    image: "deal-38.jpg",
    dealName: "Yoga Peace",
    title: "Wellness Kit",
    variantsIncluded: "8 Products",
    dealPrice: 3999.0,
    regularPrice: 6499.0,
    saving: { amount: 2500.0, percentage: 38.47 },
    status: "Active",
    createdBy: "Admin",
  },
];

function AllDeals() {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  return (
    <div className="container mx-auto px-4 py-10">
      <div className="flex items-center justify-between">
        <TypographyH2>Deals Management</TypographyH2>
        <Button onClick={() => setIsDialogOpen((prev) => !prev)}>
          Create New Deal
        </Button>
      </div>
      <DataTable
        columns={dealsColumns}
        data={dummyDealsData}
        searchColumn="dealName"
        searchPlaceholder="Search by Deal Name"
        key={"deals-table"}
      />
      <AddDeal open={isDialogOpen} onOpenchange={setIsDialogOpen} />
      <UpdateDeal />
    </div>
  );
}

export default AllDeals;
